version: '3'  

services:
  mongodb:
    image: mongo  
    container_name: mongodb  
    ports:
      - "27017:27017" 
    volumes:
      - ./data/db:/data/db  
    networks:
      - app-network  
  app:  
    build: .  
    container_name: myapp  
    ports:
      - "5678:5678"  
    environment:
      - MONGO_URL=mongodb://mongodb:27017/online-cart  
    depends_on:
      - mongodb  
    networks:
      - app-network  

networks:
  app-network:
    driver: bridge  
